model_list:
  - model_name: bedrock-claude-v3.5
    litellm_params:
      model: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0
      aws_region_name: us-east-1

litellm_settings:
    drop_params: true